name: BuildSprint96

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Initial version'
        required: true
        default: '8.0.96'  # Set your initial version here

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Environment Variables
        run: |
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Set Tag
        id: version
        run: |
          echo "::set-output name=tag::${{ env.VERSION }}"
          echo "Setting tag as ${{ env.VERSION }}"

      - name: Set up Git
        run: |
            git config --global user.email "varunteja4393@gmail.com.com"
            git config --global user.name "varunGit1256"


      - name: Push Tag
        run: |
         tag_name="${{ steps.version.outputs.tag }}"
         git tag -a $tag_name -m "Release $tag_name"
         git push origin $tag_name


      - name: Create artifact directory
        run: mkdir artifact

      - name: Copy files to artifact directory
        run: |
         shopt -s extglob
         mv !(artifact) artifact/
    
     # - name: Upload artifact
      #  uses: actions/upload-artifact@v2
       # with:
        #   name: BuildSprint400
         #  path: artifact

      - name: Upload Artifact
        run: |
         curl \
         -X POST \
         -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
         -H "Content-Type: application/zip" \
         --data-binary @artifact.zip \
         "https://uploads.github.com/repos/${{ github.repository }}/actions/artifacts/${{ github.run_id }}/zip"
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      #- name: List Artifact Contents
       # run: |
        #  ls artifact





